; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512dq | FileCheck %s --check-prefixes=AVX512DQ
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512dq,+avx512vl | FileCheck %s --check-prefixes=AVX512DQVL

declare float @llvm.fabs.f32(float)
declare double @llvm.fabs.f64(double)
declare <4 x float> @llvm.fabs.v4f32(<4 x float>)
declare <2 x double> @llvm.fabs.v2f64(<2 x double>)

define float @vrange_ss_min(float %a, float %b) {
; AVX512DQ-LABEL: vrange_ss_min:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    vrangess $6, %xmm1, %xmm0, %xmm0
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_ss_min:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangess $6, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call float @llvm.fabs.f32(float %a)
  %abs_b = call float @llvm.fabs.f32(float %b)
  %cmp = fcmp nnan olt float %abs_a, %abs_b
  %res = select nnan i1 %cmp, float %a, float %b
  ret float %res
}

define float @vrange_ss_max(float %a, float %b) {
; AVX512DQ-LABEL: vrange_ss_max:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    vrangess $7, %xmm1, %xmm0, %xmm0
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_ss_max:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangess $7, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call float @llvm.fabs.f32(float %a)
  %abs_b = call float @llvm.fabs.f32(float %b)
  %cmp = fcmp nnan ogt float %abs_a, %abs_b
  %res = select nnan i1 %cmp, float %a, float %b
  ret float %res
}

define double @vrange_sd_min(double %a, double %b) {
; AVX512DQ-LABEL: vrange_sd_min:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    vrangesd $6, %xmm1, %xmm0, %xmm0
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_sd_min:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangesd $6, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call double @llvm.fabs.f64(double %a)
  %abs_b = call double @llvm.fabs.f64(double %b)
  %cmp = fcmp nnan olt double %abs_a, %abs_b
  %res = select nnan i1 %cmp, double %a, double %b
  ret double %res
}

define double @vrange_sd_max(double %a, double %b) {
; AVX512DQ-LABEL: vrange_sd_max:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    vrangesd $7, %xmm1, %xmm0, %xmm0
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_sd_max:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangesd $7, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call double @llvm.fabs.f64(double %a)
  %abs_b = call double @llvm.fabs.f64(double %b)
  %cmp = fcmp nnan ogt double %abs_a, %abs_b
  %res = select nnan i1 %cmp, double %a, double %b
  ret double %res
}

define <4 x float> @vrange_ps_min(<4 x float> %a, <4 x float> %b) {
; AVX512DQ-LABEL: vrange_ps_min:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    # kill: def $xmm1 killed $xmm1 def $zmm1
; AVX512DQ-NEXT:    # kill: def $xmm0 killed $xmm0 def $zmm0
; AVX512DQ-NEXT:    vbroadcastss {{.*#+}} xmm2 = [NaN,NaN,NaN,NaN]
; AVX512DQ-NEXT:    vandps %xmm2, %xmm0, %xmm3
; AVX512DQ-NEXT:    vandps %xmm2, %xmm1, %xmm2
; AVX512DQ-NEXT:    vcmpltps %zmm2, %zmm3, %k1
; AVX512DQ-NEXT:    vblendmps %zmm0, %zmm1, %zmm0 {%k1}
; AVX512DQ-NEXT:    # kill: def $xmm0 killed $xmm0 killed $zmm0
; AVX512DQ-NEXT:    vzeroupper
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_ps_min:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangeps $6, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call <4 x float> @llvm.fabs.v4f32(<4 x float> %a)
  %abs_b = call <4 x float> @llvm.fabs.v4f32(<4 x float> %b)
  %cmp = fcmp nnan olt <4 x float> %abs_a, %abs_b
  %res = select nnan <4 x i1> %cmp, <4 x float> %a, <4 x float> %b
  ret <4 x float> %res
}

define <2 x double> @vrange_pd_min(<2 x double> %a, <2 x double> %b) {
; AVX512DQ-LABEL: vrange_pd_min:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    # kill: def $xmm1 killed $xmm1 def $zmm1
; AVX512DQ-NEXT:    # kill: def $xmm0 killed $xmm0 def $zmm0
; AVX512DQ-NEXT:    vmovddup {{.*#+}} xmm2 = [NaN,NaN]
; AVX512DQ-NEXT:    # xmm2 = mem[0,0]
; AVX512DQ-NEXT:    vandpd %xmm2, %xmm0, %xmm3
; AVX512DQ-NEXT:    vandpd %xmm2, %xmm1, %xmm2
; AVX512DQ-NEXT:    vcmpltpd %zmm2, %zmm3, %k1
; AVX512DQ-NEXT:    vblendmpd %zmm0, %zmm1, %zmm0 {%k1}
; AVX512DQ-NEXT:    # kill: def $xmm0 killed $xmm0 killed $zmm0
; AVX512DQ-NEXT:    vzeroupper
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_pd_min:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vrangepd $6, %xmm1, %xmm0, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call <2 x double> @llvm.fabs.v2f64(<2 x double> %a)
  %abs_b = call <2 x double> @llvm.fabs.v2f64(<2 x double> %b)
  %cmp = fcmp nnan olt <2 x double> %abs_a, %abs_b
  %res = select nnan <2 x i1> %cmp, <2 x double> %a, <2 x double> %b
  ret <2 x double> %res
}

define float @vrange_ss_min_no_nnan(float %a, float %b) {
; AVX512DQ-LABEL: vrange_ss_min_no_nnan:
; AVX512DQ:       # %bb.0:
; AVX512DQ-NEXT:    vbroadcastss {{.*#+}} xmm2 = [NaN,NaN,NaN,NaN]
; AVX512DQ-NEXT:    vandps %xmm2, %xmm0, %xmm3
; AVX512DQ-NEXT:    vandps %xmm2, %xmm1, %xmm2
; AVX512DQ-NEXT:    vcmpltss %xmm2, %xmm3, %k1
; AVX512DQ-NEXT:    vmovss %xmm0, %xmm1, %xmm1 {%k1}
; AVX512DQ-NEXT:    vmovaps %xmm1, %xmm0
; AVX512DQ-NEXT:    retq
;
; AVX512DQVL-LABEL: vrange_ss_min_no_nnan:
; AVX512DQVL:       # %bb.0:
; AVX512DQVL-NEXT:    vbroadcastss {{.*#+}} xmm2 = [NaN,NaN,NaN,NaN]
; AVX512DQVL-NEXT:    vandps %xmm2, %xmm0, %xmm3
; AVX512DQVL-NEXT:    vandps %xmm2, %xmm1, %xmm2
; AVX512DQVL-NEXT:    vcmpltss %xmm2, %xmm3, %k1
; AVX512DQVL-NEXT:    vmovss %xmm0, %xmm1, %xmm1 {%k1}
; AVX512DQVL-NEXT:    vmovaps %xmm1, %xmm0
; AVX512DQVL-NEXT:    retq
  %abs_a = call float @llvm.fabs.f32(float %a)
  %abs_b = call float @llvm.fabs.f32(float %b)
  %cmp = fcmp olt float %abs_a, %abs_b
  %res = select i1 %cmp, float %a, float %b
  ret float %res
}
